### ISSUE TITLE
Error in building Sparta app

### ISSUE THREAD

**Issue by sparkLogic** [mweagle/Sparta#55]
I'm trying out a simple Sparta application based on the "Hello World" application documented and I got this error after a `glide init; glide install; glide up;` and then run a `go run main.go`:

```
# vanguard/vendor/github.com/mweagle/Sparta
vendor/github.com/mweagle/Sparta/lambda_permissions.go:269: cannot use "vanguard/vendor/github.com/crewjam/go-cloudformation".GetAtt(configuratorResName, "Arn") (type *"vanguard/vendor/github.com/crewjam/go-cloudformation".StringExpr) as type *"vanguard/vendor/github.com/mweagle/go-cloudformation".StringExpr in assignment
vendor/github.com/mweagle/Sparta/lambda_permissions.go:270: cannot use sourceArnExpression (type *"vanguard/vendor/github.com/crewjam/go-cloudformation".StringExpr) as type *"vanguard/vendor/github.com/mweagle/go-cloudformation".StringExpr in assignment
vendor/github.com/mweagle/Sparta/lambda_permissions.go:271: cannot use "vanguard/vendor/github.com/crewjam/go-cloudformation".GetAtt(lambdaLogicalCFResourceName, "Arn") (type *"vanguard/vendor/github.com/crewjam/go-cloudformation".StringExpr) as type *"vanguard/vendor/github.com/mweagle/go-cloudformation".StringExpr in assignment
vendor/github.com/mweagle/Sparta/lambda_permissions.go:364: cannot use "vanguard/vendor/github.com/crewjam/go-cloudformation".GetAtt(configuratorResName, "Arn") (type *"vanguard/vendor/github.com/crewjam/go-cloudformation".StringExpr) as type *"vanguard/vendor/github.com/mweagle/go-cloudformation".StringExpr in assignment
vendor/github.com/mweagle/Sparta/lambda_permissions.go:365: cannot use "vanguard/vendor/github.com/crewjam/go-cloudformation".GetAtt(lambdaLogicalCFResourceName, "Arn") (type *"vanguard/vendor/github.com/crewjam/go-cloudformation".StringExpr) as type *"vanguard/vendor/github.com/mweagle/go-cloudformation".StringExpr in assignment
vendor/github.com/mweagle/Sparta/lambda_permissions.go:366: cannot use sourceArnExpression (type *"vanguard/vendor/github.com/crewjam/go-cloudformation".StringExpr) as type *"vanguard/vendor/github.com/mweagle/go-cloudformation".StringExpr in assignment
vendor/github.com/mweagle/Sparta/lambda_permissions.go:551: cannot use "vanguard/vendor/github.com/crewjam/go-cloudformation".String(rule.Name) (type *"vanguard/vendor/github.com/crewjam/go-cloudformation".StringExpr) as type *"vanguard/vendor/github.com/mweagle/go-cloudformation".StringExpr in field value
vendor/github.com/mweagle/Sparta/lambda_permissions.go:552: cannot use "vanguard/vendor/github.com/crewjam/go-cloudformation".Bool(!rule.ScanDisabled) (type *"vanguard/vendor/github.com/crewjam/go-cloudformation".BoolExpr) as type *"vanguard/vendor/github.com/mweagle/go-cloudformation".BoolExpr in field value
vendor/github.com/mweagle/Sparta/lambda_permissions.go:553: cannot use "vanguard/vendor/github.com/crewjam/go-cloudformation".Bool(!rule.Disabled) (type *"vanguard/vendor/github.com/crewjam/go-cloudformation".BoolExpr) as type *"vanguard/vendor/github.com/mweagle/go-cloudformation".BoolExpr in field value
vendor/github.com/mweagle/Sparta/lambda_permissions.go:555: cannot use make([]*"vanguard/vendor/github.com/crewjam/go-cloudformation".StringExpr, 0) (type []*"vanguard/vendor/github.com/crewjam/go-cloudformation".StringExpr) as type []*"vanguard/vendor/github.com/mweagle/go-cloudformation".StringExpr in field value
vendor/github.com/mweagle/Sparta/lambda_permissions.go:555: too many errors
```

As I'm new to using `sparta`, this is most definitely an operator error - I'm just looking for assistance to resolve the issue.

Thanks!

**Comment by sparkLogic** [comment]
If I remove the glide dependency and try a direct `go get ./...`, I still get the same error ( just providing an additional note/stack) on building the application based on http://gosparta.io/docs/intro_example/step1/

```
go get ./...                                            
# github.com/mweagle/Sparta
../../mweagle/Sparta/lambda_permissions.go:269: cannot use "github.com/crewjam/go-cloudformation".GetAtt(configuratorResName, "Arn") (type *"github.com/crewjam/go-cloudformation".StringExpr) as type *"github.com/mweagle/go-cloudformation".StringExpr in assignment
../../mweagle/Sparta/lambda_permissions.go:270: cannot use sourceArnExpression (type *"github.com/crewjam/go-cloudformation".StringExpr) as type *"github.com/mweagle/go-cloudformation".StringExpr in assignment
../../mweagle/Sparta/lambda_permissions.go:271: cannot use "github.com/crewjam/go-cloudformation".GetAtt(lambdaLogicalCFResourceName, "Arn") (type *"github.com/crewjam/go-cloudformation".StringExpr) as type *"github.com/mweagle/go-cloudformation".StringExpr in assignment
../../mweagle/Sparta/lambda_permissions.go:364: cannot use "github.com/crewjam/go-cloudformation".GetAtt(configuratorResName, "Arn") (type *"github.com/crewjam/go-cloudformation".StringExpr) as type *"github.com/mweagle/go-cloudformation".StringExpr in assignment
../../mweagle/Sparta/lambda_permissions.go:365: cannot use "github.com/crewjam/go-cloudformation".GetAtt(lambdaLogicalCFResourceName, "Arn") (type *"github.com/crewjam/go-cloudformation".StringExpr) as type *"github.com/mweagle/go-cloudformation".StringExpr in assignment
../../mweagle/Sparta/lambda_permissions.go:366: cannot use sourceArnExpression (type *"github.com/crewjam/go-cloudformation".StringExpr) as type *"github.com/mweagle/go-cloudformation".StringExpr in assignment
../../mweagle/Sparta/lambda_permissions.go:551: cannot use "github.com/crewjam/go-cloudformation".String(rule.Name) (type *"github.com/crewjam/go-cloudformation".StringExpr) as type *"github.com/mweagle/go-cloudformation".StringExpr in field value
../../mweagle/Sparta/lambda_permissions.go:552: cannot use "github.com/crewjam/go-cloudformation".Bool(!rule.ScanDisabled) (type *"github.com/crewjam/go-cloudformation".BoolExpr) as type *"github.com/mweagle/go-cloudformation".BoolExpr in field value
../../mweagle/Sparta/lambda_permissions.go:553: cannot use "github.com/crewjam/go-cloudformation".Bool(!rule.Disabled) (type *"github.com/crewjam/go-cloudformation".BoolExpr) as type *"github.com/mweagle/go-cloudformation".BoolExpr in field value
../../mweagle/Sparta/lambda_permissions.go:555: cannot use make([]*"github.com/crewjam/go-cloudformation".StringExpr, 0) (type []*"github.com/crewjam/go-cloudformation".StringExpr) as type []*"github.com/mweagle/go-cloudformation".StringExpr in field value
../../mweagle/Sparta/lambda_permissions.go:555: too many errors
```

**Comment by mweagle** [comment]
Apologies - Go vendoring is a bit of a pain and I'm in the midst of trying to isolate the github.com/crewjam/go-cloudformation dependency. If you checkout https://github.com/mweagle/Sparta/tree/0.12.0 does that resolve the issue?

**Comment by sparkLogic** [comment]
With the 0.12 branch, I was able to proceed farther until it fails with:
```
INFO[0000] runtime/internal/sys
INFO[0000] runtime/internal/atomic
INFO[0000] runtime
INFO[0001] errors
INFO[0001] runtime/cgo
INFO[0002] # runtime/cgo
INFO[0002] ld: unknown option: --build-id=none
INFO[0002] clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO[0002] Invoking rollback functions                   RollbackCount=0
Error: exit status 2
```

I'm attempting to run the SpartaHelloWorld with the command line:
> CGO_ENABLED=1 go run main.go provision -s $S3_BUCKET -l debug -i testhello

**Comment by mweagle** [comment]
I think I found the issue & have a fix incoming. In the meantime, could you try `--level info` rather than `debug`?

**Comment by mweagle** [comment]
Hi @sparkLogic - I've merged 0.12.0 to master which should resolve the `--level debug` issue. I'm running:
```
$  go version
go version go1.8.3 darwin/amd64
```
Does this resolve your issue?

**Comment by sparkLogic** [comment]
Unfortunately, I still see the issue with debug logging level cmd line argument removed.
Here is the output:
```
CGO_ENABLED=1 go run main.go provision -s $S3_BUCKET                                                                                                 ✓  1194  22:38:50
INFO[0000] ========================================
INFO[0000] Welcome to SpartaHelloWorld                   GoVersion=go1.8.3 LinkFlags= Option=provision SpartaVersion=0.12.0 UTC="2017-06-14T05:39:14Z"
INFO[0000] ========================================
INFO[0000] Provisioning service                          BuildID=41941fca3a639e606cd0ae27681e69cde099603f CodePipelineTrigger= InPlaceUpdates=false NOOP=false Tags=
INFO[0000] Verifying IAM Lambda execution roles
INFO[0000] IAM roles verified                            Count=1
INFO[0000] Checking S3 versioning                        Bucket=serverless-state-store VersioningEnabled=false
INFO[0000] Running `go generate`
INFO[0000] Compiling binary                              Name=SpartaHelloWorld.lambda.amd64
INFO[0004] # runtime/cgo
INFO[0004] ld: unknown option: --build-id=none
INFO[0004] clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO[0006] Invoking rollback functions                   RollbackCount=0
Error: exit status 2
Usage:
  main provision [flags]

Flags:
  -i, --buildID string        Optional BuildID to use
  -p, --codePipeline string   Provision for CodePipeline integration
  -h, --help                  help for provision
  -c, --inplace               If the provision operation results in *only* function updates, bypass CloudFormation
  -s, --s3Bucket string       S3 Bucket to use for Lambda source

Global Flags:
  -f, --format string    Log format [text, json] (default "text")
      --ldflags string   Go linker string definition flags (https://golang.org/cmd/link/)
  -l, --level string     Log level [panic, fatal, error, warn, info, debug] (default "info")
  -n, --noop             Dry-run behavior only (do not perform mutations)
  -t, --tags string      Optional build tags for conditional compilation

ERRO[0006] exit status 2
```

Here is my `go version`: 
> go version go1.8.3 darwin/amd64

**Comment by mweagle** [comment]
Found it - removing the `CGO_ENABLED=1` via (or set `CGO_ENABLED=0`) will resolve the issue. I'll look at detecting/resolving that in the code for 0.12.1.

**Comment by sparkLogic** [comment]
Yes, I can confirm this issue is resolved if `CGO_ENABLED=0` mode of operation. I'd love to switch to python / cgo stub when its available in 0.12.1

Thanks for driving this to closure, @mweagle

**Comment by mweagle** [comment]
Excellent - the CGO work is already available, it's just that the `CGO_ENABLED` env var isn't properly handled in the "normal" NodeJS case.

There are more docs at http://gosparta.io/docs/cgo/ && a sample project at https://github.com/mweagle/SpartaPython. Please LMK how that goes. Thanks.
